# Generated by Django 2.2.8 on 2020-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleEvent',
            fields=[
                ('bicycle_event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('bicycle_number', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('bicycle_order_id', models.CharField(max_length=100)),
                ('event_type', models.IntegerField()),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('start_lon', models.CharField(max_length=100)),
                ('start_lat', models.CharField(max_length=100)),
                ('start_addr', models.CharField(max_length=100)),
                ('end_lon', models.CharField(max_length=100)),
                ('end_lat', models.CharField(max_length=100)),
                ('end_addr', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bicycle_event',
            },
        ),
    ]
