"""
Django settings for shared_bicycle_platform_server project.

Generated by 'django-admin startproject' using Django 2.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3hb$50(+21kezfwhesk^jc#n0m@a+03t6+yh$%8o(%n4*1%l7s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').upper() == 'TRUE'

ALLOWED_HOSTS = ['*', ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'bicycle',
    'bicycle_dispatch_info',
    'bicycle_driver_record',
    'bicycle_driving_range',
    'bicycle_event',
    'bicycle_order',
    'company',
    'bicycle_beian'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'utils.middleware.CORSMiddleware',
    # 'utils.middleware.RemoteAddressMiddleware',
    'utils.middleware.MiddlewareMixin',
    'utils.middleware.PageNotFoundMiddleware'
]

ROOT_URLCONF = 'shared_bicycle_platform_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shared_bicycle_platform_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('SHARED_BICYCLE_PLATFORM_SERVER_DATABASE_NAME',
                               'shared_bicycle_platform_server'),
        'USER': os.environ.get('SHARED_BICYCLE_PLATFORM_SERVER_DATABASE_USER',
                               'postgres'),
        'PASSWORD': os.environ.get('SHARED_BICYCLE_PLATFORM_SERVER_DATABASE_PASSWORD',
                                   '123456'),
        'HOST': os.environ.get('SHARED_BICYCLE_PLATFORM_SERVER_DATABASE_HOST', '127.0.0.1'),
        'PORT': os.environ.get('SHARED_BICYCLE_PLATFORM_SERVER_DATABASE_PORT', '5432'),
        'CONN_MAX_AGE': 0,
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] [%(process)d:%(thread)d] [%(levelname)s]'
                      ' [%(name)s] [%(pathname)s:%(lineno)d] -- %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S %z',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'default': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
        },
    },
}


# Sentry
RAVEN_CONFIG = {
    'dsn': 'http://{}:{}@guard.uucin.com/{}'.format(
        os.environ.get('SENTRY_CLIENT_ID', ''),
        os.environ.get('SENTRY_CLIENT_SECRET', ''),
        os.environ.get('SENTRY_PROJECT_ID', ''),
    ),
}

if os.environ.get('ENABLE_SENTRY', 'False').upper() == 'TRUE':
    INSTALLED_APPS = INSTALLED_APPS + ['raven.contrib.django.raven_compat', ]
